### PR TITLE
Integration of TMD 7 into tablecloth

### PR DESCRIPTION
**Pull request by cnuernber**
API mainly unchanged - 

```console
FAIL aggregate default prefix changed to custom at (aggregate_test.clj:23)
Expected:
(:xxx-sum-of-b :$group-name)
Actual:
(:$group-name :xxx-sum-of-b)
Diffs: in [0] expected :xxx-sum-of-b, was :$group-name
              in [1] expected :$group-name, was :xxx-sum-of-b

FAIL replace missing values in grouped dataset at (missing_test.clj:141)
Expected:
[[1.0 2022.0 "Barry Buddon" 49]
 [0.0 2023.0 "Barry Buddon" 49]
 [2.4 2024.0 "Barry Buddon" 49]
 [3.2 2022.0 "Tentsmuir Woods" 49]
 [0.0 2023.0 "Tentsmuir Woods" 49]
 [1.4 2024.0 "Tentsmuir Woods" 49]]
Actual:
#<tech.v3.dataset.impl.dataset.Dataset$reify__23482@3c33b673>
Diffs: in [0 0] expected 1.0, was 2022.0
              in [0 1] expected 2022.0, was 49
              in [0 3] expected 49, was 1.0
              in [1 0] expected 0.0, was 2023.0
              in [1 1] expected 2023.0, was 49
              in [1 3] expected 49, was 0.0
              in [2 0] expected 2.4, was 2024.0
              in [2 1] expected 2024.0, was 49
              in [2 3] expected 49, was 2.4
              in [3 0] expected 3.2, was 2022.0
              in [3 1] expected 2022.0, was 49
              in [3 3] expected 49, was 3.2
              in [4 0] expected 0.0, was 2023.0
              in [4 1] expected 2023.0, was 49
              in [4 3] expected 49, was 0.0
              in [5 0] expected 1.4, was 2024.0
              in [5 1] expected 2024.0, was 49
              in [5 3] expected 49, was 1.4
nil
FAILURE: 2 checks failed.  (But 260 succeeded.)
```

### CODE REVIEW

**Comment by cnuernber** [comment]
- parsing sequences of maps now will retain key order - https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/dataset/io/mapseq_colmap.clj#L50
 - You can create a clojure transduce compatible rf that creates a new dataset - [mapseq-rf](https://techascent.github.io/tech.ml.dataset/tech.v3.dataset.html#var-mapseq-rf).
 
 ```clojure
user> (transduce (map identity) (ds/mapseq-rf {:dataset-name :transduced}) [{:a 1 :b 2}])
:transduced [1 2]:

| :a | :b |
|---:|---:|
|  1 |  2 |
```

**Comment by genmeblog** [comment]
Thanks! I've corrected mentioned test to compare maps instead of vectors. Relying on the order in the test wasn't good idea.

**Comment by genmeblog** [comment]
Thanks!I'm in the middle of the process (with above changes applied), so I'll probably close it.

**Comment by cnuernber** [comment]
Oh sure - I just wanted to get the lower level changes done before you got to them - closing

**Pull request closed without merging**
