### PR TITLE
docstring for fold-by

### PR DESCRIPTION
**Pull request by holyjak**

### CODE REVIEW

**Comment by genmeblog** [comment]
Hi, thanks! This week I'm away. One hint: file `tablecloth.api` is generated. Documentation should go to the actual implementation of the function, ie: https://github.com/scicloj/tablecloth/blob/master/src/tablecloth/api/fold_unroll.clj#L8 Please move it there (it will be later propagated to the `tablecloth.api` namespace).

**Comment by genmeblog** [comment]
I've copied docstring manually to the proper place and it's included in the newest version.

**Comment by holyjak** [comment]
Thank you! Sorry that I forgot to follow up on this!

**Comment by genmeblog** [comment]
No worries! Thanks for writing these docstrings.

**Pull request closed without merging**
